ghc-options:
  "$targets": -Wall -threaded -rtsopts -with-rtsopts=-xc -with-rtsopts=-N
  "$locals": -fplugin=Data.Array.Accelerate.LLVM.Native.Plugin

allow-newer: true
build:
  library-profiling: true
  executable-profiling: true
  haddock: true
  open-haddocks: false
  haddock-deps: false
  haddock-internal: false
flags:
        accelerate-blas:
                llvm-ptx: false
        accelerate:
                debug: true
                bounds-checks: true
                internal-checks: true
                nofib: true
                unsafe-checks: true
packages:
- .
resolver: lts-12.10
extra-deps:
- accelerate-1.2.0.0
- accelerate-llvm-1.2.0.0
- accelerate-llvm-native-1.2.0.0
- accelerate-blas-0.2.0.0
- llvm-hs-6.0.0
- llvm-hs-pure-6.0.0
- mersenne-random-1.0.0.1
- lens-accelerate-0.2.0.0
